name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt07
  
  precheck:
    needs: gds
    runs-on: ubuntu-22.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt07

  gl_test:
    needs: gds
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        env:
          FRAMES: 5 # Don't do all 10 frames; it'll take too long via GL
        uses: TinyTapeout/tt-gds-action/gl_test@tt07

      - name: Install ffmpeg and ImageMagick
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg imagemagick
          version: tt07 # I think naming a version builds a reusable packages cache for that name.

      - name: Convert output frames from PPMs to MP4
        shell: bash
        run: |
          pwd
          ls -al
          cd test
          ./animate.sh ./frames_out/frames.mp4

      - name: Convert output frames from PPMs to PNGs
        shell: bash
        run: |
          pwd
          ls -al
          cd test
          mkdir frames_out/png
          cd frames_out
          ../animate.sh png && cd png && tar czf ../frames.tgz *.png

      - name: Store PNGs and MP4
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: frames-gl
          path: |
            test/frames_out/frames.mp4
            test/frames_out/frames.tgz

  viewer:
    needs: gds
    runs-on: ubuntu-22.04
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt07
