name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt07
  
  precheck:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@tt07

  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@tt07

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt07

  prep_frames:
    needs: gl_test
    runs-on: ubuntu-latest
    steps:
      - name: Convert PPMs to MP4
        shell: bash
        run: |
          cd ./test
          ./animate.sh ./frames_out/frames.mp4
      - name: Convert PPMs to PNGs
        shell: bash
        run: >
          cd test
          mkdir frames_out/png
          /animate.sh ./frames_out/png
          && cd ./frames_out/png
          && tar xzf ../frames.tgz *.png

  store_frames:
    needs: prep_frames
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/upload-artifacts@4
        with:
          name: frames-gl
          path: |
            test/frames_out/frames.mp4
            test/frames_out/frames.tgz
